# Generated by Django 4.2.1 on 2024-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_todo_date_todo_location_todo_time_todo_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
