# Generated by Django 4.2.1 on 2024-02-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_todo_description_alter_todo_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='username',
        ),
    ]
