# Generated by Django 4.2.1 on 2024-02-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_todo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_id',
        ),
    ]
