# Generated by Django 4.2.1 on 2024-02-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
