# Generated by Django 4.2.1 on 2024-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
